CREATE DATABASE mecato_valluno
USE mecato_valluno;

CREATE TABLE USUARIOS (
  IDENTIFICACION VARCHAR(10) NOT NULL,
  PRIMENOMBRE VARCHAR(45) NULL,
  SEGNOMBRE VARCHAR(45) NULL,
  PRIAPELLIDO VARCHAR(45) NULL,
  SEGAPELLIDO VARCHAR(45) NULL,
  TELEFONO VARCHAR(10) NULL,
  CELULAR VARCHAR(10) NULL,
  DIRECCION VARCHAR(45) NOT NULL,
  BARRIO VARCHAR(100) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  SEXO ENUM('M', 'F') NULL DEFAULT 'M',
  LOGIN VARCHAR(10) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) NULL,
  ROL_ID INT NOT NULL,
  DEPARTAMENTOS_ID INT(100) NOT NULL,
  MUNICIPIOS_ID INT(100) NOT NULL,
  ID_SEDE INT NOT NULL,
  CREATE_DATA DATETIME NOT NULL,
  LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOTO VARCHAR(100) NULL,
  ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (IDENTIFICACION),
  CONSTRAINT fk_USUARIO_SEDE FOREIGN KEY (ID_SEDE)REFERENCES SEDE (ID),
  CONSTRAINT fk_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTOS_ID) REFERENCES DEPARTAMENTOS(ID),
  CONSTRAINT fk_MUNICIPIOS FOREIGN KEY (MUNICIPIOS_ID) REFERENCES MUNICIPIOS(ID),
  CONSTRAINT fk_ROL FOREIGN KEY (ROL_ID)REFERENCES ROL (ID));

CREATE TABLE ROL(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(45) NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

CREATE TABLE PERSMISO_ROL (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_ROL INT NOT NULL,
  ID_PERMISO INT NOT NULL,
  LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID),
  CONSTRAINT fk_BS_PERSMISOS_ROL FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID))ENGINE = InnoDB;

CREATE TABLE PERMISO(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(30) NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

CREATE TABLE MENU_ROL (
  ID INT(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  MENU_ID INT NOT NULL,
  ROL_ID INT NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID),
  CONSTRAINT fk_MENU_ROL FOREIGN KEY (MENU_ID) REFERENCES MENU(ID)) ENGINE = InnoDB;

CREATE TABLE MENU (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(45) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));

CREATE TABLE  PROGRAMA_MENU (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ID_PROGRAMA INT NOT NULL,
  MENU_ID INT NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_BS_PROGRAMA_MENU_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA(ID),
  CONSTRAINT fk_BS_PROGRAMA_MENU FOREIGN KEY (MENU_ID) REFERENCES MENU(ID))ENGINE = InnoDB;

CREATE TABLE PROGRAMA (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(45) NULL,
  ICONO VARCHAR(45) NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));

CREATE TABLE PAIS(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(45) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));

CREATE TABLE DEPARTAMENTOS(
  ID INT(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NULL,
  PAIS_ID INT NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_DEPARTAMENTOS_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS (ID));

CREATE TABLE MUNICIPIOS (
  ID INT(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NULL,
  DEPARTAMENTOS_ID INT(100) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_MUNICIPIOS_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTOS_ID)
  REFERENCES DEPARTAMENTOS(ID));


CREATE TABLE SEDE (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  TELEFONO VARCHAR(10) NULL,
  DIRECCION VARCHAR(100) NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ID_EMPRESA INT NOT NULL,
  DEPARTAMENTOS_ID INT(100) NOT NULL,
  MUNICIPIOS_ID INT(100) NOT NULL,
  DESCRIPCION VARCHAR(45) NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_BS_SEDE_BS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID),
  CONSTRAINT fk_SEDE_DEPARTAMENTOS FOREIGN KEY (`DEPARTAMENTOS_ID`)REFERENCES DEPARTAMENTOS (ID),
  CONSTRAINT fk_SEDE_MUNICIPIOS FOREIGN KEY (MUNICIPIOS_ID) REFERENCES MUNICIPIOS (ID));

CREATE TABLE EMPRESA(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  EMPNIT VARCHAR(11) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  NOMRAZSOC VARCHAR(40) NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID));


CREATE TABLE CLIENTES (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(20) NOT NULL,
  APELLIDO VARCHAR(20) NOT NULL,
  TELEFONO VARCHAR(11) NOT NULL,
  CELULAR VARCHAR(10) NULL,
  BARRIO VARCHAR(10) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ID_ROL INT NOT NULL,
  ID_EMPRESAS INT NOT NULL,
  DETALLEADICIONAL VARCHAR(120) NOT NULL,
  PAIS_ID INT NOT NULL,
  DEPARTAMENTOS_ID INT(100) NOT NULL,
  MUNICIPIOS_ID INT(100) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_CLIENTES_EMPRESAS FOREIGN KEY (ID_EMPRESAS)
  REFERENCES EMPRESA(ID),
  CONSTRAINT fk_BS_CLIENTES_BS_ROL FOREIGN KEY (ID_ROL)
  REFERENCES ROL(ID),
  CONSTRAINT fk_CLIENTES_PAIS FOREIGN KEY (PAIS_ID) REFERENCES PAIS (ID),
  CONSTRAINT fk_CLIENTES_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTOS_ID) REFERENCES DEPARTAMENTOS(ID),
  CONSTRAINT fk_CLIENTES_MUNICIPIOS  FOREIGN KEY (MUNICIPIOS_ID) REFERENCES MUNICIPIOS(ID));

CREATE TABLE PEDIDOS (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLIENTES_ID INT NOT NULL,
  SEDE_ID INT NOT NULL,
  FECHA DATE NOT NULL,
  HORA TIME NOT NULL,
  VALOR_COMPRA DECIMAL(11,2) NOT NULL,
  VALOR_DESCUENTO DECIMAL(11,2) NOT NULL,
  VALOR_IVA DECIMAL(11,2) NOT NULL,
  SUBTOTAL DECIMAL(11,2) NOT NULL,
  TOTAL_COMPRA DECIMAL(11,2) NOT NULL,
  ESTADO VARCHAR(45) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_PEDIDO_CLIENTES FOREIGN KEY (CLIENTES_ID) REFERENCES CLIENTES(ID),
  CONSTRAINT fk_PEDIDO_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE(ID))
ENGINE = InnoDB;

CREATE TABLE  CATEGORIA (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;


CREATE TABLE SUBCATEGORIA (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(100) NOT NULL,
  CATEGORIA_ID INT NOT NULL,
  PRIMARY KEY (ID),
 CONSTRAINT fk_SUBCATEGORIA_CATEGORIA FOREIGN KEY (`CATEGORIA_ID`) REFERENCES CATEGORIA(ID))
ENGINE = InnoDB;

CREATE TABLE PRODUCTO_TERMINADO(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT NOT NULL,
  PRECIO_VENTA FLOAT(100,2) NOT NULL,
  STOCK INT(255) NOT NULL,
  STOCK_MINIMO INT(255) NOT NULL,
  OFERTA VARCHAR(12) NULL,
  IMAGEN VARCHAR(255) NULL,
  CATEGORIA INT NOT NULL,
  DESCRIPCION VARCHAR(100) NOT NULL,
  IMAGES_ID INT NOT NULL,
  FECHA_FABRICACION DATETIME NOT NULL,
  FECHA_VENCIMIENTO DATETIME NOT NULL,
  PRIMARY KEY (ID),
 CONSTRAINT fk_PRODUCTO_TERMINADO_SUBCATEGORIA FOREIGN KEY (CATEGORIA) REFERENCES SUBCATEGORIA(ID))
ENGINE = InnoDB;

CREATE TABLE DETALLE_PEDIDO_PRODUCTO(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PEDIDO_ID INT NOT NULL,
  INVENTARIO_ID INT NOT NULL,
  DESCRIPCION VARCHAR(50) NULL,
  UNIDADES INT(100) NULL,
  PRECIO_UNITARIO FLOAT(100,2) NULL,
  VALOR_COMPRA DECIMAL(11,2) NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_DETALLE_PEDIDO_PRODUCTO_PEDIDO1 FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID),
  CONSTRAINT fk_DETALLE_PEDIDO_PRODUCTO_INVENTARIO FOREIGN KEY (INVENTARIO_ID) REFERENCES INVENTARIO (ID))
ENGINE = InnoDB;

CREATE TABLE INVENTARIO  (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRODUCTO_ID INT NOT NULL,
  SEDE_ID INT NOT NULL,
  LAST_UPDATE TIMESTAMP NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_INVENTARIO_PRODUCTO_TERMINADO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO_TERMINADO (ID),
  CONSTRAINT fk_INVENTARIO_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE (ID))
ENGINE = InnoDB;

CREATE TABLE PRODUCTO_INGREDIENTE(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  INGREDIENTES_ID INT NOT NULL,
  PRODUCTO_TERMINADO_ID INT NOT NULL,
  CANTIDAD INT NULL,
  UNIDAD_MEDIDA INT NOT NULL,
  DESCRIPCION VARCHAR(100) NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_PRODUCTO_INGREDIENTE_INGREDIENTES FOREIGN KEY (INGREDIENTES_ID) REFERENCES INGREDIENTE(ID),
  CONSTRAINT fk_PRODUCTO_INGREDIENTE_PRODUCTO_TERMINADO FOREIGN KEY (PRODUCTO_TERMINADO_ID) REFERENCES PRODUCTO_TERMINADO(ID),
  CONSTRAINT fk_PRODUCTO_INGREDIENTE_UNIDAD_MEDIDA1 FOREIGN KEY (UNIDAD_MEDIDA) REFERENCES UNIDAD_MEDIDA(ID))
ENGINE = InnoDB;

CREATE TABLE UNIDAD_MEDIDA(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE CHAR(2) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

CREATE TABLE MATERIA_PRIMA(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(100) NOT NULL,
  STOCK INT(100) NOT NULL,
  STOCK_MINIMO INT NULL,
  FECHA DATE NULL,
  PRECIO_COMPRA DECIMAL(11,2) NULL,
  DESCUENTO VARCHAR(2) NULL,
  DESCRIPCION VARCHAR(120) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;

CREATE TABLE COMPRA_MATERIA_PRIMA (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NUM_ORDEN_COMPRA INT NOT NULL,
  INGREDIENTES_ID INT NOT NULL,
  DESCRIPCION VARCHAR(120) NULL,
  CANTIDAD INT NULL,
  PRECIO FLOAT(100,2) NULL,
  DESCUENTO FLOAT(100,2) NULL,
  PRCIO_TOTAL FLOAT(100,2) NULL,
  PRIMARY KEY (ID),
  CONSTRAINT fk_DETALLE_COMPRA_PRODUCTO_ORDEN_COMPRA FOREIGN KEY (NUM_ORDEN_COMPRA) REFERENCES ORDEN_COMPRA(ID),
  CONSTRAINT fk_DETALLE_COMPRA_PRODUCTO_INGREDIENTES FOREIGN KEY (INGREDIENTES_ID) REFERENCES INGREDIENTE(ID))
ENGINE = InnoDB;

CREATE TABLE ORDEN_COMPRA (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PROVEEDOR_ID INT NOT NULL,
  DENTIFICACION VARCHAR(10) NOT NULL,
  FEC_ORD_COMPRA DATE NOT NULL,
  SEDE_ID INT NOT NULL,
  VALOR_COMPRA DECIMAL(11,2) NOT NULL,
  VALOR_IVA DECIMAL(11,2) NOT NULL,
  VALOR_DESCUENTO DECIMAL(100,2) NOT NULL,
  SUBTOTAL FLOAT(100,2) NOT NULL,
  TOTAL FLOAT(100,2) NOT NULL,
  STADO CHAR(10) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT fk_ORDEN_COMPRA_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(ID),
  CONSTRAINT fk_ORDEN_COMPRA_USUARIOS FOREIGN KEY (DENTIFICACION) REFERENCES USUARI0S(IDENTIFICACION),
  CONSTRAINT fk_ORDEN_COMPRA_SEDE FOREIGN KEY (SEDE_ID) REFERENCES SEDE (ID))


CREATE TABLE PROVEEDOR (
  ID INT  UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMEMPRESA VARCHAR(45) NOT NULL,
  NOMCONTACTO VARCHAR(45) NOT NULL,
  APECONTACTO VARCHAR(45) NOT NULL,
  NITEMPRESA VARCHAR(11) NOT NULL,
  DIRECCION VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(8) NOT NULL,
  CELEULAR VARCHAR(10) NOT NULL,
  LAST_UPDATE TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID))
ENGINE = InnoDB;









